### ISSUE TITLE
Exception in the response unmarshalling

### ISSUE THREAD

**Issue by code-runner-2017** [Clarifai/clarifai-php#1]
Hi, the PHP client crashes even with very simple tests copied from the Clarifai web site.
After some investigation, it seems that the request is successful, but there is a problem unmarshalling the response . This is how our response looks like:

```
{"status":{"code":10000,"description": "inputs": [
             {
                    "id": "fb461bc75b834ec4887f72fb65c2b652",
                    "data": {
                           "image": {
                                  "url": "....."
                           }
```

This is where the failure occurred `Clarifai\DTOs\Inputs\ClarifaiURLImage`:

```
if (!is_null($imageResponse->getData()->getImage()->getCrop())) {
            $image->withCrop(Crop::deserialize($imageResponse->getData()->getImage()->getCrop()));
}

```

in particular, `getCrop()` fails because the `$container` property is an empty array. We assume that getCrop() should not be called with that response.
We have solved the problem modifying `Clarifai\Grpc\Image.php` method `setCrop()` as follows:

```
public function setCrop($var)
{
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        
        if (!is_null($arr) && $arr->count() > 0) {    // <<<<<< WE ADDED THIS
            $this->crop = $arr;
        }

        return $this;
}
```

We are not sure that this is the right way to fix it, but it works so far.

Example showing the bug:

```
<?php
require_once __DIR__ . '/vendor/autoload.php';
use Clarifai\API\ClarifaiClient;
use Clarifai\DTOs\Inputs\ClarifaiURLImage;

$client = new ClarifaiClient('<APIKEY>');

$image = new ClarifaiURLImage('<IMAGE URL>');
$image->withAllowDuplicateUrl(true);

$response = $client->addInputs([
   $image,
])->executeSync();

if ($response-> isSuccessful()) {
    echo "Response is successful.\n";
} else {
    echo "Response is not successful. Reason: \n";
    echo $response->status()->description() . "\n";
    echo $response->status()->errorDetails() . "\n";
    echo "Status code: " . $response->status()->statusCode();
}

```

Thanks for your feedback.

**Comment by rok-povsic** [comment]
@code-runner-2017 Hello, thanks for the detailed information about this issue. I've tried your sample code and, interestingly, don't encounter any issue (I get "Response is successful" printed in the console). These days I am unfortunately out of office so I can only have a more detailed look at this next week. I'll keep you posted.

Note: In the latest version, `Clarifai\Grpc\Image.php` was moved to `Clarifai\Internal\_Image.php`

**Comment by rok-povsic** [comment]
@code-runner-2017 Sorry, I was checking the latest dev version instead of the latest release 0.1.1. I've now made a release 0.2.0 where this has been fixed (see here: https://github.com/Clarifai/clarifai-php/blob/60ed506ec63597b092cff231515b9a4083944d6c/src/Clarifai/DTOs/Inputs/ClarifaiURLImage.php#L93). Please try again. Thanks for reporting this.
