### ISSUE TITLE
Fatal error "Call to a member function getRegions() on null" when using new Demographics Workflow

### ISSUE THREAD

**Issue by andreaszehender** [Clarifai/clarifai-php#10]
Code:

$this->client = new ClarifaiClient($apiKey);
$fileInput	= new ClarifaiFileImage($data);
$clarifaiRequest = $this->client->workflowPredict("Demographics", $fileInput);
$clarifaiRequest->withMaxConcepts(200)->withMinValue(0.5);
$clarifaiResponse = $clarifaiRequest->executeSync();

=> Call to a member function getRegions() on null in ClarifaiOutput.php:137

Seems as if face-detector in workflow does not return data, therefore $data is null at that point.

Version 0.7.0 (installed via composer)
PHP 7.4.7

**Comment by rok-clarifai** [comment]
This library is deprecated. Please upgrade to [Clarifai PHP gRPC](https://github.com/Clarifai/clarifai-php-grpc).

Also note that there are some changes being done to the Demographics model itself. See [the upcoming API changes](https://docs.clarifai.com/product-updates/upcoming-api-changes) for more info).
