### ISSUE TITLE
Uncaught Error: Call to undefined method Clarifai\DTOs\Models\ConceptModel::client()

### ISSUE THREAD

**Issue by SafwanAd-Dardak** [Clarifai/clarifai-php#2]
Hi,

After installing the your composer plugin I tried this code: 

`use Clarifai\API\ClarifaiClient;`
`use Clarifai\DTOs\Inputs\ClarifaiURLImage;`
`use Clarifai\DTOs\Outputs\ClarifaiOutput;`
`use Clarifai\DTOs\Predictions\Concept;`
`use Clarifai\DTOs\Searches\SearchBy;`
`use Clarifai\DTOs\Searches\SearchInputsResult;`
`use Clarifai\DTOs\Models\ModelType;`

`// Skip the argument to fetch the key from the CLARIFAI_API_KEY env. variable`
`$client = new ClarifaiClient('YOUR_API_KEY');`

`$input = new ClarifaiURLImage($url);`

`$model->predict($input)`
            `->withModelVersionID($this->modelId)`
            `->executeSync();`

After executing the code I got this error:
**Fatal error:** Uncaught Error: Call to undefined method Clarifai\DTOs\Models\ConceptModel::client()

I get this error when I use the `batchPredict` function too.

I think these 2 lines need to be changed:
https://github.com/Clarifai/clarifai-php/blob/d29ebdbf344a3d2ba03bbb96c5441bc9d823e1e1/src/Clarifai/DTOs/Models/Model.php#L172 https://github.com/Clarifai/clarifai-php/blob/d29ebdbf344a3d2ba03bbb96c5441bc9d823e1e1/src/Clarifai/DTOs/Models/Model.php#L183

The first parameter should be `$this->httpClient` instead of `$this->client()`

Thanks in advance.

**Comment by AlsonPL** [comment]
https://github.com/Clarifai/clarifai-php/pull/3
