### ISSUE TITLE
Error Creating a model

### ISSUE THREAD

**Issue by geeknation** [Clarifai/clarifai-php#4]
trying to create a model using the code below results in the following error 

```
[Sun Feb 10 05:30:02.657194 2019] [:error] [pid 27099] [client 197.237.185.81:13488] PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\\\ (T_NS_SEPARATOR) in /var/www/html/libs/_src/vendor/clarifai/clarifai-php/src/Clarifai/API/CustomV2Client.php on line 6
```

the code:
```php
function createModel($modelName){
        require_once($_SERVER["DOCUMENT_ROOT"]."/libs/_src/vendor/autoload.php");
        $apiKey=$this->configs["clarifai"][0]["API_KEY"];
        $client = new Clarifai\API\ClarifaiClient($apiKey);
        $response = $client->createModel("$modelName")->executeSync();

        if ($response->isSuccessful()) {
            echo "Response is successful.\n";
        } else {
            echo "Response is not successful. Reason: \n";
            echo $response->status()->description() . "\n";
            echo $response->status()->errorDetails() . "\n";
            echo "Status code: " . $response->status()->statusCode();
        }
    } 
```

`createModel("sampleModelOne");`

**Comment by rok-povsic** [comment]
@geeknation PHP version >=7.0 is required to use this library. Are you using a version below that?

**Comment by geeknation** [comment]
Hi,
im using php 7.2

**Comment by rok-povsic** [comment]
@geeknation I've tested this library on CentOS 7 in VirtualBox, using PHP 7.2 and it works fine.

After googling the error you pasted, it seems it only happens on PHP < 5.6. For example, it appears [here](https://github.com/zendframework/zend-diactoros/issues/315). Can you double-check that it is truly PHP 7.2 that run the Clarifai code, and not some other PHP version? Calling the function `phpinfo();` will show you the PHP version and other details.

**Comment by geeknation** [comment]
Hi,
this is now okay.
i have another issue, when i make a request to create a model, i get a successful response that is a php object. How do i access the raw json output? all the object methods are private.

sample successful response from the api:

`object(Clarifai\API\ClarifaiResponse)#39 (3) { ["status":"Clarifai\API\ClarifaiResponse":private]=> object(Clarifai\DTOs\ClarifaiStatus)#38 (4) { ["statusType":"Clarifai\DTOs\ClarifaiStatus":private]=> object(Clarifai\DTOs\StatusType)#34 (1) { ["value":"Clarifai\DTOs\StatusType":private]=> string(7) "failure" } ["statusCode":"Clarifai\DTOs\ClarifaiStatus":private]=> int(21202) ["description":"Clarifai\DTOs\ClarifaiStatus":private]=> string(22) "Invalid model argument" ["errorDetails":"Clarifai\DTOs\ClarifaiStatus":private]=> string(42) "Model already exists with ID 'testmodel18'" } ["rawBody":"Clarifai\API\ClarifaiResponse":private]=> string(119) "{"status":{"code":21202,"description":"Invalid model argument","details":"Model already exists with ID 'testmodel18'"}}" ["deserialized":"Clarifai\API\ClarifaiResponse":private]=> array(0) { } }`

**Comment by geeknation** [comment]
Never Mind, i got the function rawBody() from ClarifiaiResponse.php file :-)  please update the php documentation to indicate that rawBody() is what is used to access the raw json. Its not soo obivious from this side.  . Thanks for your assistance,
