### ISSUE TITLE
StatusType is not autoloader-friendly

### ISSUE THREAD

**Issue by pontus-mp** [Clarifai/clarifai-php#5]
The class StatusType is defined in the same file as ClarifaiStatus, which prevents the PSR-4 autoloader from finding StatusType.

It is possible to work around this by tricking the autoloader into accessing ClarifaiStatus (such as adding a use-statement for ClarifaiStatus), but that is a bit fragile.

What I suggest is to move StatusType into a separate file (StatusType.php).

**Comment by rok-povsic** [comment]
@pontus-mp Hi, we've released a version 0.6.1 where `StatusType` (and other similar classes) have been put to separate files. Please let us know if this solves it for you. Thanks!

**Comment by pontus-mp** [comment]
0.6.1 works fine for us (and code cleanup tools doesn't get confused anymore), thanks!

I noticed there's still a file that should be split up (class RequestMethod in ClarifaiHttpClientInterface.php) but that seems to be internal to the package and I can't imagine that causing issues for API consumers.
